image: docker:latest

services:
    - docker:dind

stages:
    - build

before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

build:
    stage: build
    script:
        - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME .
        - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
